name: stellar_pi
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.9
  provider: ^6.0.5
  intl: ^0.20.2

  google_sign_in: ^6.1.4
  supabase_flutter: ^2.9.1
  extension_google_sign_in_as_googleapis_auth: ^2.0.13

  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0

  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env
